### ISSUE TITLE
Two background colors in the editor

### ISSUE THREAD

**Issue by brandonxoliver** [mgmeyers/obsidian-california-coast-settings#1]
Awesome theme. My new favorite!

Just wondering, is it intentionally showing two background colors in the editor? If so, how might I disable that to get one uniform color? 

I see #1E1E1E behind the cursor and #1F1F1F below that. 
Seen in both edit and preview mode, and with transparency on or off.

![Screen Capture Dec 24, 2020 at 1 41 12 PM copy](https://user-images.githubusercontent.com/45613877/103103534-aa348100-45ef-11eb-8b9b-1ccb90ebd5ba.jpeg)

**Comment by mgmeyers** [comment]
Hmm, strange. What OS are you on? Any other CSS snippets or plugins that might conflict?

**Comment by brandonxoliver** [comment]
macOS 11.1. I disabled all snippets and plugins, restarted the app, and restarted my machine and it looks like the bug is still there. Here's a vid showing that it seems to track the cursor, but only to a point. 

https://user-images.githubusercontent.com/45613877/103110194-4cb32b00-4615-11eb-9b2c-83e6408a0abd.mov

**Comment by mgmeyers** [comment]
Whoa, weird. Ok, I'll have to dig into what might be going on here.

**Comment by mgmeyers** [comment]
@brandonxoliver I've moved this issue over to the main theme repo. Going to close this one out.
