### ISSUE TITLE
Version history in Obsidian Sync shows as translucent, making it very hard to work with

### ISSUE THREAD

**Issue by cashew90** [mgmeyers/obsidian-california-coast-settings#2]
I use Obsidian's sync plugin which also offers a version history. Unfortunately, there is an issue with California Coast as the version history window in shown translucent which makes it barely readable (see screenshot). Would be great if this could be resolved. 

<img width="1424" alt="CleanShot 2021-01-18 at 11 05 20@2x" src="https://user-images.githubusercontent.com/20352339/104901176-51050680-597d-11eb-884c-8f5ec9e8830f.png">

**Comment by mgmeyers** [comment]
@cashew90 I've moved this issue over to the main theme repository:  https://github.com/mgmeyers/obsidian-california-coast-theme/issues/39

I also pushed a potential fix. Update the theme CSS and let me know if it's working for you now.
