### ISSUE TITLE
Unwanted Blank Spaces When Having Metadata

### ISSUE THREAD

**Issue by wxxedu** [mgmeyers/obsidian-california-coast-settings#3]
Hi! First of all, than you so much for this awesome plugin and awesome theme. I really love it!

For me, there is one problem though. When I have metadata, it appears that this theme would create a very long blank space between the metadata section of the Markdown file and the content of the file.

<img width="1440" alt="iShot2021-02-03 08 20 15" src="https://user-images.githubusercontent.com/36021591/106680165-15af3c80-65f9-11eb-8ec3-29da6467d755.png">

I wonder if this could be fixed. Thanks!

**Comment by mgmeyers** [comment]
@wxxedu 

I pushed a fix for this. Please update the theme (I'd also recommend installing/updating the California Coast Settings plugin) and let me know if it's working for you!

**Comment by wxxedu** [comment]
Hi! It works perfectly!!!!

Thank you soooo much for this fix and for all your hardwork into this theme. I LOVE it!
