### ISSUE TITLE
Black icons in a dark theme

### ISSUE THREAD

**Issue by tonygrr** [mgmeyers/obsidian-california-coast-settings#4]
After enabling the plugin, many icons in the dark theme become black and cannot be painted in a different color. Examples:
![image](https://user-images.githubusercontent.com/72566774/107211698-fb20fd00-6a16-11eb-8f4c-8ce170c621f1.png)
![image](https://user-images.githubusercontent.com/72566774/107211753-0c6a0980-6a17-11eb-9652-48904d4e4384.png)
![image](https://user-images.githubusercontent.com/72566774/107211863-2c99c880-6a17-11eb-9eaa-4099c19885bb.png)

**Comment by mgmeyers** [comment]
Moving this issue here: https://github.com/mgmeyers/obsidian-california-coast-theme/issues/49
